### ISSUE TITLE
预览时不能正常高亮

### ISSUE THREAD

**Issue by 99MengXin** [Jackiexiao/obsidian#1]
![螢幕快照 2020-06-30 上午10 35 41](https://user-images.githubusercontent.com/51739513/86103819-87e8fd00-babd-11ea-8d67-e939108e9d08.png)

您好，如上图所示。

请问像标题 2 不能正常高亮是 Obsidian 的 bug 吗？谢谢。

**Comment by Jackiexiao** [comment]
不是bug，`split`后面多了一个空格导致无法高亮.....，我纠正一下 @99MengXin
