### ISSUE TITLE
请问会不会考虑加入多标签功能呢？

### ISSUE THREAD

**Issue by ikali** [Jackiexiao/obsidian#5]
多页面拆分功能很好，但同时编辑多个文本的时候界面便显得比较局促了，像EmEditor编辑器，乃至mdie管理器的多标签功能可解决这种多窗口问题，又能快速定位需要编辑的文档，较为便捷。当然这是使用多年的习惯偏颇，冒昧提出拙见，见笑。

**Comment by Jackiexiao** [comment]
你得到[官方论坛/社区](https://obsidian.md/community)去反馈这个建议
